In [4]:
import numpy as np

vazio = np.empty([3,2], dtype=int)
print(vazio)
print("------")

#uma matriz só com 0
#primeiro argumento é linhas e o outro colunas
zeros = np.zeros([4,3])
print(zeros)
print("------")

#uma matriz só com um
#primeiro argumento é linhas e o outro colunas
um = np.ones([5,7])
print(um)
print("------")

#O 5 é a quantidade de colunas e linhas que você vai ter
daigonal = np.eye(5)
print(daigonal)
print("------")

[[0 0]
 [0 0]
 [0 0]]
------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------


In [5]:
#valores aletórios entre zero e um
ale = np.random.random((5))
print(ale)
print("------")

#valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("------")

#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)
print("------")


[0.14304642 0.19536553 0.84344311 0.45431519 0.56859313]
------
[-0.49523809  1.08224469  1.24676532  0.05244652 -0.64535082]
------
[[2.53114817 1.36336108 2.50365496 4.0758483 ]
 [7.73451056 0.74929872 2.43110697 5.75039854]
 [0.11613974 0.73539113 0.55511864 3.15574734]]
------


In [6]:
 #gerar aleatorio com uso de semente(a semente serve para repetir o código dps e ter o mesmo número dps)
gnr = np.random.default_rng(1)
ale4 = gnr.random(3)
print (ale4)
print("-------")

ale6 = gnr.integers(10,size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
-------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [17]:
# transformar linhas em colunas 
f = np.arange(15).reshape((3,5))
print(f)
print('------')

s = f.transpose((1,0))
print(s)

"""
Outra forma de fazer e mais fácil
#função T faz essa tranformação
s = f.T
print(s)
"""

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


'\nOutra forma de fazer\n#função T faz essa tranformação\ns = f.T\nprint(s)\n'

In [22]:
#outras formas de utilizar lógica com numpy
v = np.random.randn(4,4)
print(v)

x = (v > 0)
print(x)

z = np.where(x>0,1,-1)
print(z)

[[ 1.91698094  0.47441416 -0.03565648 -0.99118639]
 [ 0.00695618  0.47813118 -1.32280675  1.38509754]
 [-1.1541211  -2.29245296  1.57193345  1.48923509]
 [-0.56845614  0.19596067 -0.49506013 -0.04735005]]
[[ True  True False False]
 [ True  True False  True]
 [False False  True  True]
 [False  True False False]]
[[ 1  1 -1 -1]
 [ 1  1 -1  1]
 [-1 -1  1  1]
 [-1  1 -1 -1]]
