In [2]:
import numpy as np

In [5]:
#passando um vetor de dados 
mt = np.array([12,34,26,18,10])
print (mt)
print (type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [8]:
#craindo um array específico
#criando um array float com 64bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)

mtint = np.array([1,2,3],dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
[1 2 3]
<class 'numpy.ndarray'>


In [16]:
#conversao de array
mtneww = np.array([2.5,-4.7,32.1,14.5558])
print (mtneww)

mtnewwint = mtneww.astype(np.int32)
print(mtnewwint)

# podemos fazer o inverso
mt2 = mt.astype(np.float64)
print(mt2)

[ 2.5    -4.7    32.1    14.5558]
[ 2 -4 32 14]
[12. 34. 26. 18. 10.]


In [21]:
#criando uma matriz bidimensional
#Tem que ter a mesma quantidade de colunas
bimt = np.array([[1,4,5],[2,3,5],[2,32,54]])
print (bimt)

[[ 1  4  5]
 [ 2  3  5]
 [ 2 32 54]]


In [22]:
#Não repetir valores
j = np.array([1,1,2,2,33,44,55,55,44])
j = np.unique(j)
print(j)

[ 1  2 33 44 55]


In [35]:
#extração de linha de um array bidimensional 
arrayteste = np.array([[7,5],[8,3],[6,4]])
print(arrayteste)
print('-----------')
linha_arrayteste = arrayteste[0, : ]
print(linha_arrayteste)
print('-----------')
linha2_arrayteste = arrayteste[1, : ]
print(linha2_arrayteste)
print('-----------')


# todas as linhas, primeira coluna
coluna_arrayteste = arrayteste[:, 0]
print(coluna_arrayteste)
print('-----------')
coluna2_arrayteste = arrayteste[:, 1]
print(coluna2_arrayteste)

[[7 5]
 [8 3]
 [6 4]]
-----------
[7 5]
-----------
[8 3]
-----------
[7 8 6]
-----------
[5 3 4]
